-- Salon Marketplace Rebuild Script (Directus 11 Compatible)
-- Recreates the core schema. Demo content is added by the JavaScript seeder.

BEGIN;

DROP TABLE IF EXISTS public.bookings CASCADE;
DROP TABLE IF EXISTS public.employee_reviews CASCADE;
DROP TABLE IF EXISTS public.employee_schedules CASCADE;
DROP TABLE IF EXISTS public.employee_services CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.vendor_categories CASCADE;
DROP TABLE IF EXISTS public.vendors CASCADE;
DROP TABLE IF EXISTS public.categories CASCADE;
DROP TABLE IF EXISTS public.locations CASCADE;
DROP TABLE IF EXISTS public.working_hours CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.app_metrics CASCADE;
DROP TABLE IF EXISTS public.business_leads CASCADE;

CREATE TABLE public.locations (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name character varying(255) NOT NULL,
    slug character varying(255) UNIQUE NOT NULL,
    sort_order integer DEFAULT 0,
    status character varying(50) DEFAULT 'active'
);

CREATE TABLE public.categories (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name character varying(255) NOT NULL,
    slug character varying(255) UNIQUE NOT NULL,
    sort_order integer DEFAULT 0,
    status character varying(50) DEFAULT 'active'
);

CREATE TABLE public.vendors (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name character varying(255) NOT NULL,
    slug character varying(255) UNIQUE NOT NULL,
    description text,
    email character varying(255),
    phone character varying(255),
    address text,
    city character varying(255),
    area character varying(255),
    rating decimal(3,2) DEFAULT 0,
    reviews_count integer DEFAULT 0,
    is_featured boolean DEFAULT false,
    is_verified boolean DEFAULT false,
    women_only boolean DEFAULT false,
    status character varying(50) DEFAULT 'active',
    logo uuid,
    cover_image uuid,
    latitude decimal(10,8),
    longitude decimal(11,8),
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.vendor_categories (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vendors_id uuid REFERENCES public.vendors(id) ON DELETE CASCADE,
    categories_id uuid REFERENCES public.categories(id) ON DELETE CASCADE
);

CREATE TABLE public.employees (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    vendor_id uuid REFERENCES public.vendors(id) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    email character varying(255),
    photo uuid,
    bio text,
    timezone character varying(255) DEFAULT 'UTC',
    status character varying(50) DEFAULT 'active',
    sort_order integer DEFAULT 0,
    rating decimal(3,2) DEFAULT 0,
    reviews_count integer DEFAULT 0
);

CREATE TABLE public.employee_services (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id uuid REFERENCES public.employees(id) ON DELETE CASCADE,
    name character varying(255) NOT NULL,
    description text,
    price decimal(10,2) NOT NULL,
    duration_minutes integer NOT NULL DEFAULT 30,
    is_active boolean DEFAULT true,
    sort_order integer DEFAULT 0
);

CREATE TABLE public.employee_schedules (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id uuid REFERENCES public.employees(id) ON DELETE CASCADE,
    day_of_week integer NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    is_closed boolean DEFAULT false,
    sort_order integer DEFAULT 0
);

CREATE TABLE public.working_hours (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    vendor_id uuid REFERENCES public.vendors(id) ON DELETE CASCADE,
    day_of_week integer NOT NULL,
    open_time time without time zone NOT NULL,
    close_time time without time zone NOT NULL,
    is_closed boolean DEFAULT false
);

CREATE TABLE public.bookings (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id uuid REFERENCES public.employees(id),
    vendor_id uuid REFERENCES public.vendors(id),
    employee_service_id uuid REFERENCES public.employee_services(id),
    booker_email character varying(255) NOT NULL,
    booker_name character varying(255) NOT NULL,
    start_datetime timestamp with time zone NOT NULL,
    end_datetime timestamp with time zone NOT NULL,
    status character varying(50) DEFAULT 'pending',
    amount decimal(10,2),
    notes text,
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.reviews (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    vendor_id uuid REFERENCES public.vendors(id),
    customer_name character varying(255),
    customer_email character varying(255),
    rating integer CHECK (rating >= 1 AND rating <= 5),
    comment text,
    is_verified boolean DEFAULT false,
    status character varying(50) DEFAULT 'active',
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.employee_reviews (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    employee_id uuid REFERENCES public.employees(id) ON DELETE CASCADE,
    customer_name character varying(255),
    customer_email character varying(255),
    rating integer CHECK (rating >= 1 AND rating <= 5),
    comment text,
    is_verified boolean DEFAULT false,
    status character varying(50) DEFAULT 'published',
    created_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.app_metrics (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    metric_key character varying(100) UNIQUE NOT NULL,
    appointments_booked bigint NOT NULL DEFAULT 0,
    updated_at timestamp with time zone DEFAULT now()
);

CREATE TABLE public.business_leads (
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    business_name character varying(255) NOT NULL,
    contact_person character varying(255) NOT NULL,
    phone character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    category character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    status character varying(50) DEFAULT 'pending',
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);

CREATE OR REPLACE FUNCTION public.sync_vendor_review_totals()
RETURNS TRIGGER AS $$
DECLARE
    target_vendor_id uuid;
BEGIN
    target_vendor_id := COALESCE(NEW.vendor_id, OLD.vendor_id);

    UPDATE public.vendors
    SET
        rating = COALESCE((
            SELECT ROUND(AVG(rating)::numeric, 2)
            FROM public.reviews
            WHERE vendor_id = target_vendor_id
              AND status IN ('published', 'active')
        ), 0),
        reviews_count = (
            SELECT COUNT(*)
            FROM public.reviews
            WHERE vendor_id = target_vendor_id
              AND status IN ('published', 'active')
        )
    WHERE id = target_vendor_id;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION public.sync_employee_review_totals()
RETURNS TRIGGER AS $$
DECLARE
    target_employee_id uuid;
BEGIN
    target_employee_id := COALESCE(NEW.employee_id, OLD.employee_id);

    UPDATE public.employees
    SET
        rating = COALESCE((
            SELECT ROUND(AVG(rating)::numeric, 2)
            FROM public.employee_reviews
            WHERE employee_id = target_employee_id
              AND status IN ('published', 'active')
        ), 0),
        reviews_count = (
            SELECT COUNT(*)
            FROM public.employee_reviews
            WHERE employee_id = target_employee_id
              AND status IN ('published', 'active')
        )
    WHERE id = target_employee_id;

    RETURN COALESCE(NEW, OLD);
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER sync_vendor_review_totals_after_change
AFTER INSERT OR UPDATE OR DELETE ON public.reviews
FOR EACH ROW
EXECUTE FUNCTION public.sync_vendor_review_totals();

CREATE TRIGGER sync_employee_review_totals_after_change
AFTER INSERT OR UPDATE OR DELETE ON public.employee_reviews
FOR EACH ROW
EXECUTE FUNCTION public.sync_employee_review_totals();

INSERT INTO public.app_metrics (metric_key, appointments_booked)
VALUES ('live_activity', 418036);

COMMIT;
